menu:
    Blog: /
    Archive: /archives/
    JueJin: https://juejin.im/user/5be564e2f265da615d7226e5
    GitHub: https://github.com/LJTin
    About: /2019/01/21/My-Introduction/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2019
